<?php

namespace AppBundle\Repository;

/**
 * ProgramSourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgramSourceRepository extends \Doctrine\ORM\EntityRepository
{

}
