<?php

namespace AppBundle\Repository;

/**
 * VerificationCallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VerificationCallRepository extends \Doctrine\ORM\EntityRepository
{
    public function getVerificationCallsUser($iduser)
    {
        $user = $this->getEntityManager()->getRepository('AppBundle:User')->find($iduser);
        if(is_null($user))
            return null;

        $programs = $user->getProgramSources();
        $calls = array();
        foreach($programs as $prog)
            foreach($prog->getVerificationCalls() as $call)
                array_push($calls, $call);


        return $calls;
    }

    public function getVerificationCallsProgram($idprogram)
    {
        $program = $this->getEntityManager()->getRepository('AppBundle:ProgramSource')->find($idprogram);
        if(is_null($program))
            return null;

        $calls = array();
        foreach($program->getVerificationCalls() as $call)
            array_push($calls, $call);

        return $calls;
    }

}
