# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
#dunglas_angular_csrf:
#
#    token:
#        id: angular
#    header:
#        name: X-XSRF-TOKEN
#    cookie:
#        name: XSRF-TOKEN
#        expire: 0
#        path: /
#        domain: localhost
#        secure: false
#        set_on:
#            - { path: ^/.*$ }
#            - { route: /, methods: [GET, POST] }
#    secure:
#        - { path: ^/.*$, methods: [GET, POST, PUT, PATCH, LINK]  }
#        - { route: / }

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

        in_memory:
            memory: ~

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

#        main:
#            pattern: ^/
#            form_login:
#                provider: fos_userbundle
#                success_handler: authentication_success_handler
#                failure_handler: authentication_failure_handler
#            logout:
#                path:           /logout
#            anonymous:          true
        oauth_token:
            pattern:      ^/oauth/v2/token
            security:     false
        all:
            pattern:      ^/register
            security:     false

        test:
            pattern:      ^/test1
            fos_oauth:    true
            stateless:    true

        user:
                    pattern:      ^/user
                    fos_oauth:    true
                    stateless:    true
        programsource:
                    pattern:      ^/programsource
                    fos_oauth:    true
                    stateless:    true
        verificationcall:
                    pattern:      ^/verificationcall
                    fos_oauth:    true
                    stateless:    true


    access_control:
#        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/login.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/loggedIn, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/test1.*, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/user.*, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/programsource.*, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/verificationcall.*, role: IS_AUTHENTICATED_FULLY }
#          - { path: ^/profile.*, role: ROLE_USER }
#        - { path: ^/user.*, role: ROLE_USER }
