# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    authentication_success_handler:
        class: AppBundle\Security\AuthenticationSuccessHandler
        arguments: ["@router", "@doctrine.orm.entity_manager", "@event_dispatcher"]
    authentication_failure_handler:
        class: AppBundle\Security\AuthenticationFailureHandler
        arguments: ["@router", "@doctrine.orm.entity_manager", "@monolog.logger", "@event_dispatcher"]
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    app.form.profile:
            class: AppBundle\Form\ProfileType
            tags:
                - { name: form.type, alias: app_user_profile }
    app.validationchecker:
        class: AppBundle\Services\ValidationChecker
        arguments: ["@security.authorization_checker","@doctrine.orm.entity_manager"]
    app.filemanager:
        class: AppBundle\Services\FileManager
        arguments: ['%users.directory%']
